
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dagtolf.c dageometryf.c daindexf.c dacornf.c gr1f.c dainterpf.c dapreallocatef.c dacreatef.c daf.c dalocalf.c fddaf.c daghostf.c daddf.c dagtonaf.c dagetarrayf.c dadistf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscdm
LOCDIR   = src/dm/impls/da/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
