
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = drawregf.c dlinef.c dtrif.c dlinegwf.c dtextgsf.c dlinewf.c drawf.c dgcoorf.c dsetpausef.c dpointf.c drectf.c dgpausef.c dmousef.c dcoorf.c dclearf.c dsclearf.c dtextsf.c dellipsef.c dpointsf.c dpausef.c dviewpf.c dbufff.c dsflushf.c dmarkerf.c dflushf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscsys
LOCDIR   = src/sys/classes/draw/interface/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
