
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS  =
CFLAGS   =
FFLAGS   =
SOURCEC  = statef.c pinitf.c inheritf.c destroyf.c ptypef.c tagmf.c optionsf.c gcommf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	  = libpetscsys
LOCDIR	  = src/sys/objects/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
