
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = iscoloringf.c isblockf.c isdifff.c iscompf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	 = libpetscvec
LOCDIR	 = src/vec/is/is/utils/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
