
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS =
CFLAGS   =
FFLAGS   =
SOURCEC  = plextreef.c plexexodusiif.c plexorientf.c plexsubmeshf.c plexgeometryf.c plexgeneratef.c plexpointf.c plexgmshf.c plexpartitionf.c plexrefinef.c plexf.c plexdistributef.c plexinterpolatef.c plexbcf.c plexcreatef.c plexcgnsf.c plexlabelf.c plexindicesf.c plexfemf.c plexreorderf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscdm
LOCDIR   = src/dm/impls/plex/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
